# Generated by Django 4.0.3 on 2022-03-07 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_thread_tweet_thread_number_tweet_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retweet',
            name='tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retweets', to='tweet.tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='tweet.thread'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='thread_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
